export const drivers = [
  {
    id: "1",
    name: "Michael Smith",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    carImage: "https://i.imgur.com/Ro5gxv7.jpeg",
    carModel: "Toyota Camry",
    license: "ABC 123",
    color: "Black",
    distance: "0.3 miles away",
    rating: 4.9,
    trips: 1250,
    location: { latitude: 40.7125, longitude: -74.005 },
    address: "456 Elm Street, New York, NY",
    experience: "5 years",
    acceptance: "98%",
    languages: ["English"],
    music: ["Jazz", "Pop"],
    reviews: [
      {
        name: "Alice",
        comment: "Smooth ride and clean car.",
        stars: 5,
        time: "2 days ago",
      },
    ],
  },
  {
    id: "2",
    name: "Sarah Johnson",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    carImage: "https://i.imgur.com/lbERP1a.jpeg",
    carModel: "Honda Civic",
    license: "XYZ 789",
    color: "Blue",
    distance: "0.5 miles away",
    rating: 4.8,
    trips: 1040,
    location: { latitude: 40.713, longitude: -74.007 },
    address: "789 Maple Ave, New York, NY",
    experience: "4 years",
    acceptance: "95%",
    languages: ["English", "Spanish"],
    music: ["Hip-Hop", "RnB"],
    reviews: [
      {
        name: "John",
        comment: "Driver was very polite.",
        stars: 4,
        time: "1 week ago",
      },
    ],
  },
  {
    id: "3",
    name: "David Wilson",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    carImage: "https://i.imgur.com/JOefeAO.jpeg",
    carModel: "Tesla Model 3",
    license: "DEF 456",
    color: "White",
    distance: "0.8 miles away",
    rating: 4.7,
    trips: 980,
    location: { latitude: 40.7135, longitude: -74.004 },
    address: "321 Broadway, New York, NY",
    experience: "3 years",
    acceptance: "92%",
    languages: ["English", "French"],
    music: ["Classical", "Electronic"],
    reviews: [
      {
        name: "Sophia",
        comment: "Very quiet ride. Loved the EV experience!",
        stars: 5,
        time: "3 days ago",
      },
    ],
  },
  {
    id: "4",
    name: "Emily Brown",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    carImage: "https://i.imgur.com/8yNc08N.jpeg",
    carModel: "Hyundai Sonata",
    license: "GHI 789",
    color: "Red",
    distance: "1.2 miles away",
    rating: 4.9,
    trips: 1100,
    location: { latitude: 40.714, longitude: -74.006 },
    address: "654 Park Lane, New York, NY",
    experience: "6 years",
    acceptance: "97%",
    languages: ["English", "Portuguese"],
    music: ["Afrobeats", "Soul"],
    reviews: [
      {
        name: "Daniel",
        comment: "Emily was super friendly and arrived quickly.",
        stars: 5,
        time: "5 days ago",
      },
    ],
  },
  {
    id: "5",
    name: "Daniel Garcia",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    carImage: "https://i.imgur.com/KcjPF8Y.jpeg",
    carModel: "Kia Optima",
    license: "JKL 321",
    color: "Gray",
    distance: "1.5 miles away",
    rating: 4.6,
    trips: 890,
    location: { latitude: 40.7145, longitude: -74.008 },
    address: "789 Sunset Blvd, New York, NY",
    experience: "2 years",
    acceptance: "90%",
    languages: ["English", "Spanish"],
    music: ["Reggaeton", "Trap"],
    reviews: [
      {
        name: "Liam",
        comment: "Nice music choice and safe driving.",
        stars: 4,
        time: "2 weeks ago",
      },
    ],
  },
];

export const rideOptions = [
  { id: "1", type: "Economy", price: "$12-15", eta: "3 min away" },
  { id: "2", type: "Comfort", price: "$18-22", eta: "5 min away" },
  { id: "3", type: "XL", price: "$25-30", eta: "7 min away" },
];
